version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.apache.ignite:ignite-kubernetes
    versions:
    - 2.9.1
  - dependency-name: org.apache.ignite:ignite-spring
    versions:
    - 2.9.1
  - dependency-name: org.apache.ignite:ignite-core
    versions:
    - 2.9.1
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: io.github.openfeign:feign-core
    versions:
    - "11.0"
  - dependency-name: io.github.openfeign:feign-slf4j
    versions:
    - "11.0"
  - dependency-name: io.github.openfeign:feign-jackson
    versions:
    - "11.0"
