name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: s4u/maven-settings-action@v1
      name: Setup maven settings.xml
      with:
        servers: '[{"id": "docker.io", "username": "${{ secrets.dockerhub_user }}", "password": "${{ secrets.dockerhub_pass }}"}]'
    - name: Build with Maven
      run: mvn -B deploy --file pom.xml

